// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_hwatso02.Models;

namespace Mission06_hwatso02.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20230221005308_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_hwatso02.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Family"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Musical"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Rom-Com"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Sci-Fi"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Suspense"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Other"
                        });
                });

            modelBuilder.Entity("Mission06_hwatso02.Models.MovieCollection", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<int>("RatingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RatingId");

                    b.ToTable("collection");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 11,
                            Director = "Jaume Collet-Serra",
                            Edited = false,
                            Notes = "Amazing Liam Neeson movie",
                            RatingId = 3,
                            Title = "Non-Stop",
                            Year = (ushort)2014
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 6,
                            Director = "Randal Kleiser",
                            Edited = false,
                            LentTo = "Mom",
                            RatingId = 2,
                            Title = "Grease",
                            Year = (ushort)1978
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 1,
                            Director = "Jaume Collet-Serra",
                            Edited = false,
                            LentTo = "Kara and Dad",
                            RatingId = 3,
                            Title = "The Italian Job",
                            Year = (ushort)2003
                        });
                });

            modelBuilder.Entity("Mission06_hwatso02.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RatingName")
                        .HasColumnType("TEXT");

                    b.HasKey("RatingId");

                    b.ToTable("ratings");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            RatingName = "G"
                        },
                        new
                        {
                            RatingId = 2,
                            RatingName = "PG"
                        },
                        new
                        {
                            RatingId = 3,
                            RatingName = "PG-13"
                        },
                        new
                        {
                            RatingId = 4,
                            RatingName = "R"
                        });
                });

            modelBuilder.Entity("Mission06_hwatso02.Models.MovieCollection", b =>
                {
                    b.HasOne("Mission06_hwatso02.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mission06_hwatso02.Models.Rating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
