// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_hwatso02.Models;

namespace Mission06_hwatso02.Migrations
{
    [DbContext(typeof(MoviesContext))]
    partial class MoviesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_hwatso02.Models.MovieCollection", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("collection");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Action",
                            Director = "Jaume Collet-Serra",
                            Edited = false,
                            Notes = "Amazing Liam Neeson movie",
                            Rating = 2,
                            Title = "Non-Stop",
                            Year = (ushort)2014
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Musical",
                            Director = "Randal Kleiser",
                            Edited = false,
                            LentTo = "Mom",
                            Rating = 1,
                            Title = "Grease",
                            Year = (ushort)1978
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Action",
                            Director = "Jaume Collet-Serra",
                            Edited = false,
                            LentTo = "Kara and Dad",
                            Rating = 2,
                            Title = "The Italian Job",
                            Year = (ushort)2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
